"""empty message

Revision ID: 11afa025baeb
Revises: 8c92c4b8b5a6
Create Date: 2023-03-14 14:52:57.379796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11afa025baeb'
down_revision = '8c92c4b8b5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('index', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'index')
    # ### end Alembic commands ###
