"""empty message

Revision ID: 688da2a29df2
Revises: a3efd76672b0
Create Date: 2023-03-14 17:55:30.928731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688da2a29df2'
down_revision = 'a3efd76672b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('messages_conversation_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_conversation_id_fkey', 'messages', 'conversations', ['conversation_id'], ['id'])
    # ### end Alembic commands ###
