"""empty message

Revision ID: 6c8741a5764a
Revises: 11afa025baeb
Create Date: 2023-03-14 15:43:55.890740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c8741a5764a'
down_revision = '11afa025baeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('messages', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'updated_at')
    op.drop_column('conversations', 'updated_at')
    # ### end Alembic commands ###
