"""empty message

Revision ID: a3efd76672b0
Revises: 6c8741a5764a
Create Date: 2023-03-14 17:40:46.438555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3efd76672b0'
down_revision = '6c8741a5764a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('content', sa.Text(), nullable=False))
    op.drop_column('messages', 'message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('messages', 'content')
    # ### end Alembic commands ###
